# Site settings
title: "Roland's blog"
header-img: img/home-bg.jpg
email: jotteres@gmail.com
copyright_name: Roland Schneider
description: "Random stuff about mountainbiking, coding, music and life in general"
baseurl: ""
url: "http://www.schneiderroland.de"
twitter_username: jerosch
github_username:  jerosch
facebook_username:  jotteres
disqus_username: jerosch
google_analytics_code: UA-65302967-1


# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]